kind: Service
apiVersion: v1
metadata:
  name: demo-app
  namespace: devops-demo

spec:
  selector:
    app: demo-app
  ports:
    - name: http
      port: 5100
      targetPort: 5100
  type: ClusterIP
